//! Integration tests against the h5py-generated NWB 2.7 fixture.
//!
//! ## Fixture
//!
//! `D:\consus\data\nwb\nwb_fixture_v2_7.nwb` is generated by
//! `data/nwb/gen_nwb_fixture.py` using h5py 3.x.  Content specification:
//!
//! | Path | Type | Values |
//! |------|------|--------|
//! | root `neurodata_type_def` | FixedString attr | `"NWBFile"` |
//! | root `nwb_version` | FixedString attr | `"2.7.0"` |
//! | root `identifier` | FixedString attr | `"test_session_001"` |
//! | root `session_description` | FixedString attr | `"Integration test fixture"` |
//! | root `session_start_time` | FixedString attr | `"2023-01-15T10:00:00.000000+00:00"` |
//! | `acquisition/test_timeseries/data` | f64[5] | `[0.1,0.2,0.3,0.4,0.5]` |
//! | `acquisition/test_timeseries/timestamps` | f64[5] | `[0.0,0.1,0.2,0.3,0.4]` |
//! | `acquisition/test_timeseries_rate/data` | i16[3] | `[100,200,300]` |
//! | `acquisition/test_timeseries_rate/starting_time` | f64 scalar | `5.0`, rate attr = 1000.0 f32 |
//! | `Units/spike_times` | f64[5] | `[1.0,1.5,2.0,2.5,3.0]` |
//! | `Units/spike_times_index` | u64[2] | `[2,5]` |
//! | `Units/id` | u64[2] | `[0,1]` |
//! | `electrodes/location` | VariableString[3] | `["CA1","CA2","CA3"]` |
//! | `electrodes/group_name` | VariableString[3] | `["tetrode1","tetrode2","tetrode3"]` |
//! | `general/subject` attrs | FixedString | subject_id, species, sex, age, description |
//!
//! ## Invariants verified
//!
//! 1. `NwbFile::open` succeeds on h5py-generated files.
//! 2. `session_metadata` reads all three required string attributes.
//! 3. `nwb_version` returns `NwbVersion::V2_7`.
//! 4. `list_acquisition` returns the two time-series group paths.
//! 5. `time_series` decodes f64 data + timestamps (no precision loss).
//! 6. `time_series` decodes i16 data via integer-promotion to f64 (100.0, 200.0, 300.0).
//! 7. `time_series` decodes scalar starting_time + rate attribute.
//! 8. `units_table` decodes VectorData + VectorIndex into per-unit spike times.
//! 9. `electrode_table` decodes variable-length string columns (CA1/CA2/CA3).
//! 10. `subject` reads all five optional subject metadata fields.

use consus_nwb::file::NwbFile;
use consus_nwb::version::NwbVersion;

const FIXTURE_PATH: &str = "data/nwb/nwb_fixture_v2_7.nwb";

/// Floating-point relative tolerance for f64 comparisons derived from f64
/// round-trip precision (IEEE 754: ULP for values near 0.1 is ~1.4e-17).
/// We use 1e-12 to accommodate any f64→bytes→f64 round-trip rounding.
fn near(a: f64, b: f64) -> bool {
    if b == 0.0 {
        a.abs() < 1e-14
    } else {
        ((a - b) / b).abs() < 1e-12
    }
}

#[test]
fn real_file_nwb_v2_7_fixture_verification() {
    // Runtime presence check: skip gracefully if the fixture is absent so
    // CI machines without the generated file do not fail hard.
    let bytes = match std::fs::read(FIXTURE_PATH) {
        Ok(b) => b,
        Err(_) => {
            eprintln!(
                "SKIP: fixture not found at {FIXTURE_PATH} — run data/nwb/gen_nwb_fixture.py"
            );
            return;
        }
    };

    // ── 1. Open ──────────────────────────────────────────────────────────
    let file = NwbFile::open(&bytes).expect("NwbFile::open must succeed on h5py NWB fixture");

    // ── 2. Session metadata ──────────────────────────────────────────────
    let meta = file
        .session_metadata()
        .expect("session_metadata must not fail");
    assert_eq!(meta.identifier(), "test_session_001", "identifier mismatch");
    assert_eq!(
        meta.session_description(),
        "Integration test fixture",
        "session_description mismatch"
    );
    assert_eq!(
        meta.session_start_time(),
        "2023-01-15T10:00:00.000000+00:00",
        "session_start_time mismatch"
    );

    // ── 3. NWB version ───────────────────────────────────────────────────
    let version = file.nwb_version().expect("nwb_version must succeed");
    assert_eq!(version, NwbVersion::V2_7, "expected NwbVersion::V2_7");

    // ── 4. list_acquisition ──────────────────────────────────────────────
    let mut acq_paths = file
        .list_acquisition()
        .expect("list_acquisition must succeed");
    acq_paths.sort();
    assert_eq!(
        acq_paths,
        vec![
            "acquisition/test_timeseries".to_owned(),
            "acquisition/test_timeseries_rate".to_owned(),
        ],
        "list_acquisition paths mismatch"
    );

    // ── 5. TimeSeries — f64 data + timestamps ────────────────────────────
    let ts1 = file
        .time_series("acquisition/test_timeseries")
        .expect("time_series(test_timeseries) must succeed");
    assert_eq!(ts1.name(), "test_timeseries", "ts1 name mismatch");
    let d1 = ts1.data();
    assert_eq!(d1.len(), 5, "ts1 data length must be 5");
    let expected_data = [0.1_f64, 0.2, 0.3, 0.4, 0.5];
    for (i, (&got, &exp)) in d1.iter().zip(expected_data.iter()).enumerate() {
        assert!(near(got, exp), "ts1.data[{i}]: got {got}, expected {exp}");
    }
    let ts1_ts = ts1.timestamps().expect("ts1 must have timestamps");
    assert_eq!(ts1_ts.len(), 5, "ts1 timestamps length must be 5");
    let expected_ts = [0.0_f64, 0.1, 0.2, 0.3, 0.4];
    for (i, (&got, &exp)) in ts1_ts.iter().zip(expected_ts.iter()).enumerate() {
        assert!(
            near(got, exp),
            "ts1.timestamps[{i}]: got {got}, expected {exp}"
        );
    }
    assert!(
        ts1.starting_time().is_none(),
        "ts1 must not have starting_time"
    );
    assert!(ts1.rate().is_none(), "ts1 must not have rate");

    // ── 6. TimeSeries — i16 data via integer promotion ───────────────────
    let ts2 = file
        .time_series("acquisition/test_timeseries_rate")
        .expect("time_series(test_timeseries_rate) must succeed");
    assert_eq!(ts2.name(), "test_timeseries_rate", "ts2 name mismatch");
    let d2 = ts2.data();
    assert_eq!(d2.len(), 3, "ts2 data length must be 3");
    // i16 100 → f64 100.0 exactly (integer promotion, no precision loss)
    assert_eq!(d2[0], 100.0_f64, "ts2.data[0] must be 100.0 (i16→f64)");
    assert_eq!(d2[1], 200.0_f64, "ts2.data[1] must be 200.0 (i16→f64)");
    assert_eq!(d2[2], 300.0_f64, "ts2.data[2] must be 300.0 (i16→f64)");
    assert!(ts2.timestamps().is_none(), "ts2 must not have timestamps");

    // ── 7. TimeSeries — starting_time + rate ─────────────────────────────
    let st = ts2.starting_time().expect("ts2 must have starting_time");
    assert!(near(st, 5.0), "starting_time: got {st}, expected 5.0");
    let rate = ts2.rate().expect("ts2 must have rate");
    // np.float32(1000.0) → stored as f32, read back as f64; exact at this value
    assert!(near(rate, 1000.0), "rate: got {rate}, expected 1000.0");

    // ── 8. UnitsTable — VectorData / VectorIndex roundtrip ───────────────
    let ut = file.units_table().expect("units_table must succeed");
    assert_eq!(ut.num_units(), 2, "must have 2 units");
    let spu = ut.spike_times_per_unit();
    assert_eq!(spu[0], vec![1.0_f64, 1.5], "unit0 spike times mismatch");
    assert_eq!(
        spu[1],
        vec![2.0_f64, 2.5, 3.0],
        "unit1 spike times mismatch"
    );
    let ids = ut.ids().expect("units must have ids");
    assert_eq!(ids, &[0u64, 1], "units ids mismatch");

    // ── 9. ElectrodeTable — variable-length string columns ───────────────
    // This is the primary verification of the new VariableString dataset
    // decode path introduced in read_string_dataset.
    let et = file
        .electrode_table()
        .expect("electrode_table must succeed");
    assert_eq!(et.len(), 3, "must have 3 electrodes");

    let row0 = et.get(0).expect("electrode row 0 must exist");
    assert_eq!(row0.id, 0, "electrode 0 id");
    assert_eq!(row0.location, "CA1", "electrode 0 location (VL string)");
    assert_eq!(
        row0.group_name, "tetrode1",
        "electrode 0 group_name (VL string)"
    );

    let row1 = et.get(1).expect("electrode row 1 must exist");
    assert_eq!(row1.id, 1, "electrode 1 id");
    assert_eq!(row1.location, "CA2", "electrode 1 location (VL string)");
    assert_eq!(
        row1.group_name, "tetrode2",
        "electrode 1 group_name (VL string)"
    );

    let row2 = et.get(2).expect("electrode row 2 must exist");
    assert_eq!(row2.id, 2, "electrode 2 id");
    assert_eq!(row2.location, "CA3", "electrode 2 location (VL string)");
    assert_eq!(
        row2.group_name, "tetrode3",
        "electrode 2 group_name (VL string)"
    );

    // ── 10. Subject metadata ─────────────────────────────────────────────
    let subj = file.subject().expect("subject must succeed");
    assert_eq!(
        subj.subject_id().as_deref(),
        Some("mouse_001"),
        "subject_id"
    );
    assert_eq!(subj.species().as_deref(), Some("Mus musculus"), "species");
    assert_eq!(subj.sex().as_deref(), Some("M"), "sex");
    assert_eq!(subj.age().as_deref(), Some("P60D"), "age");
    assert_eq!(
        subj.description().as_deref(),
        Some("Test mouse"),
        "description"
    );
}
