//! Roundtrip tests: h5py writer → consus reader.
//!
//! ## Purpose
//!
//! These tests verify that consus can correctly read HDF5 files produced by
//! h5py.  Each test:
//!
//! 1. Invokes `data/gen_h5py_compressed.py --case <name> --file <tmp>` to
//!    produce a fixture file using h5py.
//! 2. Opens the file with consus.
//! 3. Asserts the expected dataset structure and values.
//!
//! All tests skip gracefully when Python or h5py is unavailable.
//!
//! ## Coverage
//!
//! | Case                  | Dtype   | Shape     | Compression | Chunks |
//! |-----------------------|---------|-----------|-------------|--------|
//! | `deflate_1d_i32`      | int32   | (8,)      | deflate/6   | (4,)   |
//! | `deflate_2d_f64`      | float64 | (4,6)     | deflate/6   | (2,3)  |
//! | `deflate_3d_i32`      | int32   | (2,3,4)   | deflate/6   | (2,3,4)|
//! | `contiguous_u8`       | uint8   | (5,)      | none        | -      |
//! | `contiguous_f32`      | float32 | (4,)      | none        | -      |
//! | `contiguous_i16`      | int16   | (4,)      | none        | -      |
//! | `chunked_1d_f32_deflate` | float32 | (8,)   | deflate/6   | (4,)   |

use core::num::NonZeroUsize;
use std::path::PathBuf;
use std::process::Command;

use consus_core::{ByteOrder as CoreByteOrder, Datatype};
use consus_hdf5::file::Hdf5File;
use consus_io::MemCursor;

// ---------------------------------------------------------------------------
// Infrastructure helpers (mirrors roundtrip_consus_to_h5py.rs)
// ---------------------------------------------------------------------------

fn gen_script() -> PathBuf {
    PathBuf::from(env!("CARGO_MANIFEST_DIR"))
        .parent()
        .unwrap()
        .parent()
        .unwrap()
        .join("data")
        .join("gen_h5py_compressed.py")
}

fn find_python() -> Option<String> {
    for candidate in &[r"D:\miniforge3\python.exe", "python3", "python"] {
        let ok = Command::new(candidate)
            .args(["-c", "import h5py"])
            .output()
            .map(|o| o.status.success())
            .unwrap_or(false);
        if ok {
            return Some((*candidate).to_string());
        }
    }
    None
}

/// Generate an HDF5 fixture file via h5py and return its bytes.
///
/// Returns `None` when Python/h5py is unavailable or the generator fails.
fn generate_fixture(case: &str) -> Option<Vec<u8>> {
    let script = gen_script();
    if !script.exists() {
        eprintln!("Skipping {case}: gen script not found at {script:?}");
        return None;
    }
    let python = find_python()?;

    let tmp = tempfile::NamedTempFile::new().ok()?;
    let tmp_path = tmp.path().to_owned();

    let output = Command::new(&python)
        .args([
            script.to_str().unwrap(),
            "--case",
            case,
            "--file",
            tmp_path.to_str().unwrap(),
        ])
        .output()
        .ok()?;

    if !output.status.success() {
        let stderr = String::from_utf8_lossy(&output.stderr);
        eprintln!("Skipping {case}: gen script failed: {stderr}");
        return None;
    }

    // Read the generated bytes from the path (avoids cursor-position issues).
    std::fs::read(&tmp_path).ok()
}

fn open_file(bytes: Vec<u8>) -> Hdf5File<MemCursor> {
    let cursor = MemCursor::from_bytes(bytes);
    Hdf5File::open(cursor).expect("open HDF5 file")
}

// ---------------------------------------------------------------------------
// Datatype helpers
// ---------------------------------------------------------------------------

fn i32_le() -> Datatype {
    Datatype::Integer {
        bits: NonZeroUsize::new(32).unwrap(),
        byte_order: CoreByteOrder::LittleEndian,
        signed: true,
    }
}

fn f64_le() -> Datatype {
    Datatype::Float {
        bits: NonZeroUsize::new(64).unwrap(),
        byte_order: CoreByteOrder::LittleEndian,
    }
}


fn f32_le() -> Datatype {
    Datatype::Float {
        bits: NonZeroUsize::new(32).unwrap(),
        byte_order: CoreByteOrder::LittleEndian,
    }
}

fn i16_le() -> Datatype {
    Datatype::Integer {
        bits: NonZeroUsize::new(16).unwrap(),
        byte_order: CoreByteOrder::LittleEndian,
        signed: true,
    }
}

// ---------------------------------------------------------------------------
// Tests
// ---------------------------------------------------------------------------

/// h5py writes deflate-compressed int32 array (8,) → consus reads and
/// verifies shape, dtype, and values 0..7.
///
/// ## Invariant
///
/// consus correctly decompresses and reads zlib-format deflate data
/// produced by h5py (filter ID 1).
#[test]
fn h5py_deflate_1d_i32_readable_by_consus() {
    let Some(bytes) = generate_fixture("deflate_1d_i32") else {
        return;
    };
    let hf = open_file(bytes);

    let addr = hf.open_path("/deflate_1d_i32").expect("open path");
    let ds = hf.dataset_at(addr).expect("dataset_at");

    assert_eq!(ds.datatype, i32_le(), "dtype mismatch");
    assert_eq!(ds.shape.current_dims().as_slice(), &[8usize], "shape mismatch");

    let raw = hf.read_chunked_dataset_all_bytes(addr).expect("read chunked");
    let values: Vec<i32> = raw
        .chunks_exact(4)
        .map(|b| i32::from_le_bytes(b.try_into().unwrap()))
        .collect();
    let expected: Vec<i32> = (0..8).collect();
    assert_eq!(values, expected, "values mismatch");
}

/// h5py writes deflate-compressed float64 2-D array (4,6) → consus reads
/// and verifies shape, dtype, and values 0.0..23.0.
///
/// ## Invariant
///
/// Multi-dimensional chunked deflate data from h5py is correctly decoded
/// by consus.
#[test]
fn h5py_deflate_2d_f64_readable_by_consus() {
    let Some(bytes) = generate_fixture("deflate_2d_f64") else {
        return;
    };
    let hf = open_file(bytes);

    let addr = hf.open_path("/deflate_2d_f64").expect("open path");
    let ds = hf.dataset_at(addr).expect("dataset_at");

    assert_eq!(ds.datatype, f64_le(), "dtype mismatch");
    assert_eq!(ds.shape.current_dims().as_slice(), &[4usize, 6], "shape mismatch");

    let raw = hf.read_chunked_dataset_all_bytes(addr).expect("read chunked");
    let values: Vec<f64> = raw
        .chunks_exact(8)
        .map(|b| f64::from_le_bytes(b.try_into().unwrap()))
        .collect();
    let expected: Vec<f64> = (0..24).map(|i| i as f64).collect();
    assert_eq!(values, expected, "values mismatch");
}

/// h5py writes deflate-compressed int32 3-D array (2,3,4) → consus reads
/// and verifies all 24 elements.
///
/// ## Invariant
///
/// 3-D chunked deflate data from h5py (single-chunk, entire dataset) is
/// correctly read by consus.
#[test]
fn h5py_deflate_3d_i32_readable_by_consus() {
    let Some(bytes) = generate_fixture("deflate_3d_i32") else {
        return;
    };
    let hf = open_file(bytes);

    let addr = hf.open_path("/deflate_3d_i32").expect("open path");
    let ds = hf.dataset_at(addr).expect("dataset_at");

    assert_eq!(ds.datatype, i32_le(), "dtype mismatch");
    assert_eq!(ds.shape.current_dims().as_slice(), &[2usize, 3, 4], "shape mismatch");

    let raw = hf.read_chunked_dataset_all_bytes(addr).expect("read chunked");
    let values: Vec<i32> = raw
        .chunks_exact(4)
        .map(|b| i32::from_le_bytes(b.try_into().unwrap()))
        .collect();
    let expected: Vec<i32> = (0..24).collect();
    assert_eq!(values, expected, "values mismatch");
}

/// h5py writes a contiguous uint8 array (5,) → consus reads and verifies.
///
/// ## Invariant
///
/// Contiguous uint8 datasets from h5py are correctly read by consus.
#[test]
fn h5py_contiguous_u8_readable_by_consus() {
    let Some(bytes) = generate_fixture("contiguous_u8") else {
        return;
    };
    let hf = open_file(bytes);

    let addr = hf.open_path("/contiguous_u8").expect("open path");
    let ds = hf.dataset_at(addr).expect("dataset_at");

    // uint8 byte-order is not applicable (single byte); skip dtype assertion.
    assert_eq!(ds.shape.current_dims().as_slice(), &[5usize], "shape mismatch");

    let data_addr = ds.data_address.expect("data_address");
    let mut buf = vec![0u8; 5];
    hf.read_contiguous_dataset_bytes(data_addr, 0, &mut buf)
        .expect("read contiguous");
    assert_eq!(buf, vec![10u8, 20, 30, 40, 50], "values mismatch");
}

/// h5py writes a contiguous float32 array (4,) → consus reads and verifies.
///
/// ## Invariant
///
/// Contiguous float32 datasets from h5py are correctly read by consus.
#[test]
fn h5py_contiguous_f32_readable_by_consus() {
    let Some(bytes) = generate_fixture("contiguous_f32") else {
        return;
    };
    let hf = open_file(bytes);

    let addr = hf.open_path("/contiguous_f32").expect("open path");
    let ds = hf.dataset_at(addr).expect("dataset_at");

    assert_eq!(ds.datatype, f32_le(), "dtype mismatch");
    assert_eq!(ds.shape.current_dims().as_slice(), &[4usize], "shape mismatch");

    let data_addr = ds.data_address.expect("data_address");
    let mut buf = vec![0u8; 16];
    hf.read_contiguous_dataset_bytes(data_addr, 0, &mut buf)
        .expect("read contiguous");
    let values: Vec<f32> = buf
        .chunks_exact(4)
        .map(|b| f32::from_le_bytes(b.try_into().unwrap()))
        .collect();
    assert_eq!(values, vec![1.5f32, 2.5, 3.5, 4.5], "values mismatch");
}

/// h5py writes a contiguous int16 array (4,) → consus reads and verifies.
///
/// ## Invariant
///
/// Contiguous int16 datasets from h5py are correctly read by consus.
#[test]
fn h5py_contiguous_i16_readable_by_consus() {
    let Some(bytes) = generate_fixture("contiguous_i16") else {
        return;
    };
    let hf = open_file(bytes);

    let addr = hf.open_path("/contiguous_i16").expect("open path");
    let ds = hf.dataset_at(addr).expect("dataset_at");

    assert_eq!(ds.datatype, i16_le(), "dtype mismatch");
    assert_eq!(ds.shape.current_dims().as_slice(), &[4usize], "shape mismatch");

    let data_addr = ds.data_address.expect("data_address");
    let mut buf = vec![0u8; 8];
    hf.read_contiguous_dataset_bytes(data_addr, 0, &mut buf)
        .expect("read contiguous");
    let values: Vec<i16> = buf
        .chunks_exact(2)
        .map(|b| i16::from_le_bytes(b.try_into().unwrap()))
        .collect();
    assert_eq!(values, vec![-100i16, 0, 100, 200], "values mismatch");
}

/// h5py writes a deflate-compressed float32 chunked array (8,) chunks (4,)
/// → consus reads and verifies values 0.0..7.0.
///
/// ## Invariant
///
/// Deflate-compressed float32 chunked datasets from h5py are correctly
/// decoded by consus.
#[test]
fn h5py_chunked_1d_f32_deflate_readable_by_consus() {
    let Some(bytes) = generate_fixture("chunked_1d_f32_deflate") else {
        return;
    };
    let hf = open_file(bytes);

    let addr = hf.open_path("/chunked_1d_f32_deflate").expect("open path");
    let ds = hf.dataset_at(addr).expect("dataset_at");

    assert_eq!(ds.datatype, f32_le(), "dtype mismatch");
    assert_eq!(ds.shape.current_dims().as_slice(), &[8usize], "shape mismatch");

    let raw = hf.read_chunked_dataset_all_bytes(addr).expect("read chunked");
    let values: Vec<f32> = raw
        .chunks_exact(4)
        .map(|b| f32::from_le_bytes(b.try_into().unwrap()))
        .collect();
    let expected: Vec<f32> = (0..8).map(|i| i as f32).collect();
    assert_eq!(values, expected, "values mismatch");
}
